# Generated by Django 5.2.9 on 2025-12-20 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('sequence_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'sequence_id'], name='events_even_channel_78f121_idx')],
                'unique_together': {('channel', 'sequence_id')},
            },
        ),
    ]
